# Generated by Django 3.2.5 on 2021-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
