# Generated by Django 3.2.5 on 2021-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketingpreference_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='subscribed',
            field=models.BooleanField(null=True),
        ),
    ]
