# Generated by Django 3.2.5 on 2021-08-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestEmail',
            new_name='Guest',
        ),
    ]
